<?php
echo '<div class="container d-flex justify-content-evenly mt-auto">
<div>
<a href="howtouse.php">
<img src="assets/question-square-fill.svg" style="width: 100%; height: auto" class="mb-2" alt="...">
</a>
<h3>How To Use</h3>
</div>
<div>
<a href="fuzzing.php">
<img src="assets/shield-shaded.svg" style="width: 90%; height: auto" class="mb-2" alt="...">
</a>
<h3>Start Fuzzing</h3>
</div>

<div>
 <a href="jobhistory.php">
<img src="assets/clock-history.svg" style="width: 100%; height: auto" class="mb-2" alt="...">
</a>
<h3>Job History</h3>
</div>
</div>';
?>
