<?php
echo '
<nav class="navbar navbar-expand-lg">
  <div class="container">
    <a class="navbar-brand" href="Navigation"><h2>Fuzzing platform<em>.</em></h2></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="login.php">Login</a>
        </li>
  <li class="nav-item">
          <a class="nav-link" href="aboutus.php">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="aboutafl.php">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="index.php">User Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="exit.php">Sign out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
';
?>
