<?php
echo '<div class="container d-flex justify-content-evenly mt-auto">
<div>
<h3>Job History</h3>
</div>
<div style="border-left: solid black">
</div>
<div>
<p>Previous Items Fuzzed</p>
<table>
 <tr>
   <th>Person 1</th>
   <th>Person 2</th>
   <th>Person 3</th>
 </tr>
 <tr>
   <td>Emil</td>
   <td>Tobias</td>
   <td>Linus</td>
 </tr>
 <tr>
   <td>16</td>
   <td>14</td>
   <td>10</td>
 </tr>
</table> 
</div>
</div>';
?>
