<?php
echo '<head>
  <meta charset="utf-8">
  <meta name="lang" content="en">
  <meta name="title" content="Project#23">
  <meta name="description" content="Landing Page">
  <meta name="author" content="Group 23">
  <title>AFL Fuzzing</title>
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="core/bootstrap/bootstrap.min.css">
  <link rel="stylesheet" href="assets/css/fontawesome.css">
  <link rel="stylesheet" href="assets/css/style.css">

  <script src="core/bootstrap/bootstrap.bundle.min.js"></script>
  </head>';
?>
