<?php
echo '<h2 class="text-center">Welcome To The User Dashboard</h2>';
echo '<div class="container d-flex justify-content-evenly mt-auto">
<div>
<img src="assets/question-square-fill.svg" style="width: 100%; height: auto" class="mb-2" alt="...">
<h3>How To Use</h3>
</div>
<div>
<img src="assets/shield-shaded.svg" style="width: 90%; height: auto" class="mb-2" alt="...">
<h3>Start Fuzzing</h3>
</div>
<div>
<img src="assets/clock-history.svg" style="width: 100%; height: auto" class="mb-2" alt="...">
<h3>Job History</h3>
</div>
</div>';
?>
