<?php
echo '<head>
  <meta charset="utf-8">
  <meta name="lang" content="en">
  <meta name="title" content="Project#23 Rough Concept">
  <meta name="description" content="Landing Page">
  <meta name="author" content="Group 23">
  <title>Project#23 Rough Concept</title>
  <link rel="stylesheet" href="core/bootstrap/bootstrap.min.css">
  <script src="core/bootstrap/bootstrap.bundle.min.js"></script>
  </head>';
?>
